title: Ernie Lu
logo: /assets/img/logo.png
description: |
  Mechanical Engineering Ph.D. (UCLA, in progress)
  Mechanical Engineering M.S. (UCLA)
  Aerospace Engineering B.S. (UCI) | Mechanical Engineering B.S. (UCI)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
