title: Ernie Lu
logo: /assets/img/logo.png
description: |
  Mechanical Engineering Ph.D. (UCLA, in progress)<br>
  Mechanical Engineering M.S. (UCLA)<br>
  Aerospace Engineering B.S. (UCI)<br>
  Mechanical Engineering B.S. (UCI)<br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
