title: Ernie Lu
logo: /assets/img/logo.png
description: Mechanical Engineering Ph.D. Mechanical Engineering M.S. Aerospace Engineering B.S.; Mechanical Engineering B.S.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
